### ISSUE TITLE
Just a question not an issue

### ISSUE THREAD

**Issue by v217** [berenddeboer/xplain2sql#2]
Sorry for posting this question as an issue and not on the mailing list, but I wonder how explain compares to the recent data manipulation language [cql](https://www.categoricaldata.net/)?

**Comment by berenddeboer** [comment]
Questions are most welcome!

I think Xplain was always meant to be used by non-specialists. It reads easy, and writing statements is easy. CQL looks very technical too me. I don't know enough to discuss technical differences, Xplain is based on set theory.
